export {default as Home} from './home/Home';
export {default as Profile} from './profile/Profile';
export {default as Item} from './item/Item';
export {default as Create} from './create/Create';
export {default as Login} from './login/Login';
export {default as Register} from './register/Register';
export {default as Collection} from './collection/collectionstat';
export {default as Feed} from './Feed/Feed'
export {default as ProductDetail} from './product_detail/Product_detail'
